spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mylibrary?allowMultiQueries=true
    username: root
    password: "001212"
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapperLocations: classpath:Mapper/*.xml




